name: Git Version

on:
  workflow_dispatch:
  push:
    branches:
    - develop
    paths:
    - src/*/**
    - appsettings/*

defaults:
  run:
    shell: pwsh

jobs:
  build-and-deploy:
    environment: vidara.portal-dev
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:

    # checkout the repo
    - name: Fetch all history for all tags and branches
      uses: actions/checkout@v2
      run: |
        git fetch --prune --unshallow

  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      # gitversion/execute step omitted for brevity

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: gittools/actions/gitversion/setup@v0
        name: Install GitVersion  

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7

      - run: |
          echo "FullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}"
          
  display-semver:
    name: Display Semantic Version
    runs-on: ubuntu-latest
    needs: calculate-version
    env:
      SEMVER: ${{ needs.calculate-version.outputs.semVer }}
    steps:
      - name: Display version
        run: |
          echo SemVer: $SEMVER
