name: Git Version

on:
  workflow_dispatch:
  push:
    branches:
    - develop
    paths:
    - src/*/**
    - appsettings/*

defaults:
  run:
    shell: pwsh

jobs:
  build-and-deploy:
    environment: vidara.portal-dev
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:

      # checkout the repo
      - name: Fetch all history for all tags and branches
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

  calculate-version:
    name: Calculate Version
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
    steps:
      # gitversion/execute step omitted for brevity

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: gittools/actions/gitversion/setup@v0.9.13
        name: Install GitVersion  
        with:
          versionSpec: '5.x'

      - uses: gittools/actions/gitversion/execute@v0.9.13
        name: Determine Version
        id: gitversion
          
  display-semver:
    name: Display Semantic Version
    runs-on: ubuntu-latest
    needs: calculate-version
    env:
      SEMVER: ${{ needs.calculate-version.outputs.semVer }}
    steps:
      - name: Display version
        run: |
          echo SemVer: $env:SEMVER

  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    needs: calculate-version
    env:
      SEMVER: ${{ needs.calculate-version.outputs.semVer }}

    steps:

    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Dotnet Restore
      run: dotnet restore ./src/project

    - name: Dotnet Build
      run: dotnet build --configuration Release ./src/project

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.2
      with:
        # Artifact name
        name: GitHubActionsHelloWorldConsoleDownloadableArtifact${{ needs.calculate-version.outputs.semVer }} #.zip will be added automatically
        path: ./bin/release/net6.0/*.*
